### ISSUE TITLE
Credits page for Civic Tech Jobs

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#123] opened 2022-01-19 02:29 UTC
### Dependency

- [x] #283
- [x] #284

### Overview

we need to cite and provide credit to the images we are using, so that we will not be plagiarizing any content

### Action Items

- [x] See how HackforLA currently has set up its credits page
- [ ] Review if we can use a similar format 

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

[HackforLA credits page](https://www.hackforla.org/credits/)

**Comment by kcoronel** [comment] 2024-02-14 06:33
This is a duplicate of issue #273

**Closed by kcoronel** 2024-02-14 06:33 UTC
Labels: role: UI/UX - Design, size: 2pt, feature: Documentation, P3: Med
